### ISSUE TITLE
Blank page 

### ISSUE THREAD

**Issue by xd20111** [BlackHacker511/BlackNET#17]
Localhost is all going well but when i use blacknet script on 000webhost it showing blank page

**Comment by BlackHacker511** [comment]
Hello,

BlackNET does not work on any free web hosting
because it uses functions and methods that free hosting does not allow
if you want to you could try to turn xampp to an online server 
you will find articles on how to do it online
or get a cheap shared hosting you could find some good one out there
everyone I talked to who uses BlackNET usually they installed it on a VPS but if you can't afford one 
shared hosting will serve you just fine

Enjoy
