### ISSUE TITLE
Unable to connect: SQLSTATE[HY000] [1045] ProxySQL Error: Access denied for user 'root'@'2a02:4780:bad:f00d::6' (using password: YES)

### ISSUE THREAD

**Issue by technicaldada** [BlackHacker511/BlackNET#19]
This type of error got when try to installing from http://URL.com/install.php

Unable to connect: SQLSTATE[HY000] [1045] ProxySQL Error: Access denied for user 'root'@'2a02:4780:bad:f00d::6' (using password: YES)

I have upload the files on 000webhost... and updated the database name in database.php file

**Comment by BlackHacker511** [comment]
Please check your config file and like i said before BlackNET does not work on any free web hosting
because it uses functions and methods that free hosting does not allow
if you want to you could try to turn xampp to an online server
you will find articles on how to do it online
or get a cheap shared hosting you could find some good one out there
everyone I talked to who uses BlackNET usually they installed it on a VPS but if you can't afford one
shared hosting will serve you just fine

**Comment by BlackHacker511** [comment]
I will try to install it my self on 000webhost and i see what's the issue and maybe if it fixable i'll fix it on the new version

**Comment by BlackHacker511** [comment]
i installed it without no issues
update the Database.php
with DB username, DB name,DB password and for the host use localhost
i will push the new version tomorrow with 000webhost compatibility

**Comment by technicaldada** [comment]
looks good ... but why i cant do it.. waiting for the new version.. thanks a lot
