### ISSUE TITLE
Occasional Page Not Found 

### ISSUE THREAD

**Issue by velocity010** [BlackHacker511/BlackNET#46]
![Desktop Screenshot 2020 01 30 - 16 33 11 32](https://user-images.githubusercontent.com/59211180/73492229-46252080-437e-11ea-9d27-b04c36310530.png)
 Sometimes when i try to access the log in page this pops up, and theres no definite way i know of fixing it (already installed php)

**Comment by BlackHacker511** [comment]
It is not supposed to do that there is no redirection to install.php

did you get the "please install" page because if yes it's the hosting problem they have a database query limit if go up this limit they shutdown your access for an hour that result in BlackNET redirect you to the install page even when you already installed it.

**Comment by velocity010** [comment]
So after an hour it’ll fix itself?

**Comment by BlackHacker511** [comment]
@velocity010 yes it should fixed it self after an hour or two if you get the same error in the future go to phpmyadmin and check if get an error there it should be something like this "you exceeded the query limit"
