### ISSUE TITLE
Building source vb

### ISSUE THREAD

**Issue by panpansh** [BlackHacker511/BlackNET#50]
Same using source code version with existing bin/Debug, no stub.
ref : https://github.com/BlackHacker511/BlackNET/issues/34
When I delete all files from bin/Debug : AssemblyDefinition, ModuleDefinition, TypeDefinition, Instruction, Code not defined && can't find Mono.Cecil
there is something wrong.
Best regards

**Comment by panpansh** [comment]
Correction on my part for the moment.
I have never touched vb.
I noticed that I had to import the library already Mono.Cecil.
I continue my investigation

**Comment by panpansh** [comment]
Finish,
did you mean stub.exe the svchost.exe(renamed) generated by the PHPStub project ?

**Comment by panpansh** [comment]
Maybe not,
I'm online in php panel but no command received (from panel) to client.
Maybe I'm wrong,
Good night @BlackHacker511

**Comment by panpansh** [comment]
There is compatibility between schtask, startup ans stealth ?
Can I debug starting stub project with default Host ?
Regards

**Comment by BlackHacker511** [comment]
Use one of them don't try to use them all together i recommend using stealth mode because stealth mode uses startup for persistence you can use startup alone without the the stealth and if you want to Schtask enable Elevate UAC because Schtask requires administrative privileges and startup does not.
