### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by cvv2f** [BlackHacker511/BlackNET#53]
After uploading the new update on my host i build a new stub and i test not working kindly check and fix or maybe am the one missing something

**Comment by Ejwhite25** [comment]
> After uploading the new update on my host i build a new stub and i test not working kindly check and fix or maybe am the one missing something

Same problem here.

**Comment by s1l3n7h0s7** [comment]
They mean once building a stub for the new v3 update it doesnt call back to
the panel


On Feb 7, 2020 at 07:33, Ejwhite25 <notifications@github.com> wrote:

After uploading the new update on my host i build a new stub and i test not
working kindly check and fix or maybe am the one missing something

Same problem here.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BlackHacker511/BlackNET/issues/53?email_source=notifications&email_token=AKSP2S2HCVS2XD3KAXGGXTTRBTXD7A5CNFSM4KRHFPF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOELBY7CQ#issuecomment-583241610>,
or unsubscribe

**Comment by BlackHacker511** [comment]
Did you add a connection password

**Comment by agentReef** [comment]
I try to rebuild(erase all and reinstall) and find out the panel size is much more smaller than before,I just want to make sure the lastest release 3.0 is a upgrade pack, or I can just install it as the old way?

thank you

**Comment by BlackHacker511** [comment]
I removed a lot of useless SVG and font files from the panel file structure that why it's smaller and yes you can install it the old just remove the current panel delete the database and install it the old way i don't do upgrade packs this the whole code

**Comment by cvv2f** [comment]
> Did you add a connection password
> 
> The connections password is important without it there is no connection the BlackNET default password is: Au9SmrqefaAr1DYFnZEpgGaZYdepAs5i

Still no connection have use a fresh domain and host after install no connection between the system and the panel

**Comment by BlackHacker511** [comment]
See this video
https://youtu.be/eIOd8Xo7CvY
